version: 2
jobs:
  build:
    docker:
      - image: nixorg/nix:circleci
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          key: nix-store
      - run:
          name: Install cachix
          command: |
            nix-env -iA cachix -f https://cachix.org/api/v1/install
      - run:
          name: Build
          command: |
            USER=root cachix use cargo2nix
            cachix push cargo2nix -w &
            nix-build -A packages.x86_64-linux.ci --show-trace
            nix-build -A packages.x86_64-linux.examples -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/e74894146a42ba552ebafa19ab2d1df7ccbc1738.tar.gz --show-trace
            nix-shell --show-trace --run exit
          no_output_timeout: 5h
      - save_cache:
          key: nix-store
          paths:
            - /nix
