version: 2
jobs:
  build:
    docker:
      - image: nixorg/nix:circleci
    resource_class: medium
    steps:
      - checkout
      - restore_cache:
          key: nix-store
      - run:
          name: Install cachix
          command: |
            nix-env -iA cachix -f https://cachix.org/api/v1/install
      - run:
          name: Build
          command: |
            USER=root cachix use cargo2nix
            cachix push cargo2nix -w &
            nix-build -A ci --show-trace
            nix-build -A examples -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/e34208e10033315fddf6909d3ff68e2d3cf48a23.tar.gz --show-trace
            nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/e34208e10033315fddf6909d3ff68e2d3cf48a23.tar.gz --show-trace --run cargo2nix 
          no_output_timeout: 5h
      - save_cache:
          key: nix-store
          paths:
            - /nix
