# This file was @generated by cargo2nix 0.8.1.
# It is not intended to be manually edited.

{
  release ? true,
  rootFeatures ? [
    "hello-world-with-lib/default"
  ],
  rustPackages,
  buildRustPackages,
  hostPlatform,
  mkRustCrate,
  rustLib,
  lib,
}:
let
  inherit (rustLib) fetchCratesIo fetchCrateLocal fetchCrateGit fetchCrateAlternativeRegistry expandFeatures decideProfile genDrvsByProfile;
  profilesByName = {
  };
  rootFeatures' = expandFeatures rootFeatures;
  overridableMkRustCrate = f:
    let
      drvs = genDrvsByProfile profilesByName ({ profile, profileName }: mkRustCrate ({ inherit release profile; } // (f profileName)));
    in { compileMode ? null, profileName ? decideProfile compileMode release }:
      let drv = drvs.${profileName}; in if compileMode == null then drv else drv.override { inherit compileMode; };
in
{
  cargo2nixVersion = "0.8.1";
  workspace = {
    hello-world-with-lib = rustPackages.unknown.hello-world-with-lib."0.1.0";
  };
  "unknown".hello-world-with-lib."0.1.0" = overridableMkRustCrate (profileName: rec {
    name = "hello-world-with-lib";
    version = "0.1.0";
    registry = "unknown";
    src = fetchCrateLocal ./.;
  });
  
}
