[package]
name = "hello-world"
version = "0.1.0"
authors = ["gjz010 <gjz010@gjz010.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }
windows = { version = "0.54.0", features = ["Win32_UI_WindowsAndMessaging"] }
